# Generated by Django 4.2 on 2025-01-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_quiz_time_limit_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
